name: parkingclic
description: "Aplicativo que ayuda a encontrar un lugar seguro para tu medio de transporte"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0 
  get_it: ^7.2.0
  retrofit: ^4.1.0
  logger: any
  dio: ^5.5.0+1
  injectable: ^2.4.4
  # navigation
  auto_route: ^8.2.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  google_fonts: 6.2.1
  firebase_messaging: ^15.0.3
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.13.1
  dartz: ^0.10.1
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.2.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^8.0.0
  mockito: ^5.3.0
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/ic_logo_app.png"

flutter:
  uses-material-design: true
  assets:
  - images/
